### PR TITLE
Update testing

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by rapenchukd** [comment]
Awesome, I'm out of town for most of the day and will take a gander at this tonight, but looks good

**Comment by shortdudey123** [comment]
sounds good, thanks!

**Comment by shortdudey123** [comment]
@rapenchukd any feedback from your end?

**Comment by rapenchukd** [comment]
Hey, sorry, been swamped past few days, took a look last night and it all looks really good, doing some final tests today and if all goes well will be merged :+1:

**Comment by shortdudey123** [comment]
Cool, thanks!

**Comment by rapenchukd** [comment]
Good stuff, man. Props to you! Thank you for the awesome additions!

**Comment by shortdudey123** [comment]
no problem :)

**Pull request merged**
